# Generated by Django 5.0.3 on 2024-03-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_student_performance_tutee_tutee_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Tutee', 'Tutee')], max_length=10),
        ),
    ]
