# Generated by Django 5.0.3 on 2024-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='hours_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='meetings_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='tutee_performance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hours_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='meetings_created',
            field=models.IntegerField(default=0),
        ),
    ]
