# Generated by Django 5.0.3 on 2024-03-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tutee_hours_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutee',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutees', to='users.tutor'),
        ),
    ]
