# Generated by Django 5.0.3 on 2024-03-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tutee_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutees', to='users.tutor'),
        ),
    ]
