# Generated by Django 5.0.3 on 2024-03-22 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_tutee_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutees', to='users.tutor'),
        ),
    ]
