# Generated by Django 5.0.3 on 2024-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_tutee_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Tutee', 'Tutee'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
