# Generated by Django 5.0.3 on 2024-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
