# Generated by Django 5.0.3 on 2024-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(max_length=100),
        ),
    ]
